name: "MJ"
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: check out master
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: install package
        run: npm install
      - name: build vue code
        run: npm run build
      - name: GitHub Pages action
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-gh-pages@3bdd7da7d7d089f3323b0d9f6fdcd59d492a2541
        uses: peaceiris/actions-gh-pages@v3.7.0
        with:
          # Set a SSH private key from repository secret value for pushing to the remote branch.
          #deploy_key: # optional
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          github_token: ${{ secrets.GITHUB_TOKEN }} # optional
          # Set a personal access token for pushing to the remote branch.
          #personal_token: # optional
          # Set a target branch for deployment.
          publish_branch: develop # optional, default is gh-pages
          # Set an input directory for deployment.
          publish_dir: ./dist # optional, default is public
          # Set an destination subdirectory for deployment.
          #destination_dir: # optional, default is
          # Set an external repository (owner/repo).
          #external_repository: # optional
          # If empty commits should be made to the publication branch
          #allow_empty_commit: # optional, default is false
          # If existing files in the publish branch should be not removed before deploying
          #keep_files: # optional, default is false
          # Keep only the latest commit on a GitHub Pages branch
          #force_orphan: # optional, default is false
          # Set Git user.name
          #user_name: # optional
          # Set Git user.email
          #user_email: # optional
          # Set a custom commit message with a triggered commit hash
          #commit_message: # optional
          # Set a custom full commit message without a triggered commit hash
          #full_commit_message: # optional
          # Set tag name
          #tag_name: # optional
          # Set tag message
          #tag_message: # optional
          # Enable the GitHub Pages built-in Jekyll
          #enable_jekyll: # optional, default is false
          # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
          #disable_nojekyll: # optional, default is false
